DROP DATABASE IF EXISTS airports_dw;

CREATE DATABASE airports_dw;

USE airports_dw;

CREATE TABLE dim_airport (
    AIRPORT_ID SMALLINT(6),
    AIRPORTNAME VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    PRIMARY KEY (AIRPORT_ID)
);

CREATE TABLE dim_time (
    TIME_ID DATETIME,
    YEAR_ID INT,
    MONTH_ID INT,
    MONTH_NAME VARCHAR(255),
    DAY_ID INT,
    PRIMARY KEY (TIME_ID)
);

CREATE TABLE dim_airline (
    AIRLINE_ID SMALLINT(6),
    AIRLINE_NAME VARCHAR(255),
    PRIMARY KEY (AIRLINE_ID)
);

CREATE TABLE dim_airplane (
    AIRPLANE_ID INT(11),
    TYPE_ID INT(11),
    PRIMARY KEY (AIRPLANE_ID)
);

CREATE TABLE fact_flight (
    FLIGHT_ID INT,
    AIRPORT_ORIG SMALLINT(6),
    AIRPORT_DEST SMALLINT(6),
    DEPARTURE DATETIME,
    ARRIVAL DATETIME,
    AIRLINE_ID SMALLINT(6),
    AIRPLANE_ID INT(11),
    N_PASSENGERS INT,
    REVENUE DECIMAL(10,2),
    PRIMARY KEY (FLIGHT_ID),
    FOREIGN KEY (AIRPORT_ORIG) REFERENCES dim_airport (AIRPORT_ID),
    FOREIGN KEY (AIRPORT_DEST) REFERENCES dim_airport (AIRPORT_ID),
    FOREIGN KEY (DEPARTURE) REFERENCES dim_time (TIME_ID),
    FOREIGN KEY (ARRIVAL) REFERENCES dim_time (TIME_ID),
    FOREIGN KEY (AIRLINE_ID) REFERENCES dim_airline (AIRLINE_ID),
    FOREIGN KEY (AIRPLANE_ID) REFERENCES dim_airplane (AIRPLANE_ID)
);