DROP DATABASE IF EXISTS airports_dw;

CREATE DATABASE airports_dw;

USE airports_dw;

CREATE TABLE dim_airport_orig (
    AIRPORTNAME VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    PRIMARY KEY (AIRPORTNAME)
);

CREATE TABLE dim_airport_dest (
    AIRPORTNAME VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    PRIMARY KEY (AIRPORTNAME)
);

CREATE TABLE dim_time_dept (
    DAY_ID INT,
    MONTH_ID INT,
    YEAR_ID INT,
    PRIMARY KEY (DAY_ID, MONTH_ID, YEAR_ID)
);

CREATE TABLE dim_time_arrv (
    DAY_ID INT,
    MONTH_ID INT,
    YEAR_ID INT,
    PRIMARY KEY (DAY_ID, MONTH_ID, YEAR_ID)
);

CREATE TABLE dim_airline (
    AIRLINENAME VARCHAR(255),
    PRIMARY KEY (AIRLINENAME)
);

CREATE TABLE dim_airplane (
    TYPE_ID INT,
    PRIMARY KEY (TYPE_ID)
);

CREATE TABLE fact_flight (
    FLIGHT_ID INT,
    AIRPORTORIGIN VARCHAR(255),
    AIRPORTDESTIN VARCHAR(255),
    DAY_DEPT INT,
    MONTH_DEPT INT,
    YEAR_DEPT INT,
    DAY_ARRV INT,
    MONTH_ARRV INT,
    YEAR_ARRV INT,
    AIRLINENAME VARCHAR(255),
    AIRPLANE_TYPE INT(11),
    PASSENGERS INT,
    REVENUE DECIMAL(10,2),
    PRIMARY KEY (FLIGHT_ID),
    FOREIGN KEY (AIRPORTORIGIN) REFERENCES dim_airport_orig (AIRPORTNAME),
    FOREIGN KEY (AIRPORTDESTIN) REFERENCES dim_airport_dest (AIRPORTNAME),
    FOREIGN KEY (DAY_DEPT, MONTH_DEPT, YEAR_DEPT) REFERENCES dim_time_dept (DAY_ID, MONTH_ID, YEAR_ID),
    FOREIGN KEY (DAY_ARRV, MONTH_ARRV, YEAR_ARRV) REFERENCES dim_time_arrv (DAY_ID, MONTH_ID, YEAR_ID),
    FOREIGN KEY (AIRLINENAME) REFERENCES dim_airline (AIRLINENAME),
    FOREIGN KEY (AIRPLANE_TYPE) REFERENCES dim_airplane (TYPE_ID)
);